### ISSUE TITLE
Create examples with PDFs/Txt & Folders 

### ISSUE THREAD

**Issue by BillionShields** [RMNCLDYO/gemini-ai-toolkit#3]
**Is your feature request related to a problem? Please describe.**
Chat with PDFs in a batch

**Describe the solution you'd like**
sample code with some flag when complete response is given 

**Describe alternatives you've considered**
manually in Ai 

**Additional context**

**Comment by RMNCLDYO** [comment]
Hey,

Just wanted to let you know that your feature request for chatting with PDFs in a batch has been added in v1.3!

You can now use the `multimodal` mode when chatting with the model. This allows you to provide files at the start of the conversation and continue chatting and uploading files during the conversation with the new `/upload` command.

See usage details in the README [here](https://github.com/RMNCLDYO/gemini-ai-toolkit/blob/main/README.md).

I'm going to close this issue now since it's taken care of. If you run into any other issues or have more suggestions, feel free to open a new one.

Thanks for the input!

Cheers
